# specify a directory to install
cask_args appdir: '~/Applications'

tap 'homebrew/bundle'

brew 'helm'
brew 'htop'
brew 'jq'
brew 'minikube'
brew 'nmap'
brew 'siege'
brew 'watch'
brew 'youtube-dl'
brew 'telnet'
brew 'speedtest-cli'
brew 'warrensbox/tap/tfswitch'
brew 'terragrunt'
brew 'vault'
brew 'bash'
brew 'neofetch'
brew 'vim'
brew 'pass'
brew 'fping'
