# specify a directory to install
cask_args appdir: '~/Applications'

tap 'homebrew/bundle'

brew 'helm'
brew 'htop'
brew 'jq'
brew 'minikube'
brew 'nmap'
brew 'watch'
brew 'youtube-dl'
brew 'telnet'
brew 'speedtest-cli'
brew 'terragrunt'
brew 'bash'
brew 'neofetch'
brew 'vim'
brew 'pass'
brew 'fping'
brew 'grip'
brew 'ansible'
brew 'awscli'
brew 'pre-commit'
brew 'tmux'


# Casks
cask 'google-cloud-sdk'
cask 'google-chrome'
cask 'firefox'
cask 'tor-browser'
cask 'skype'
cask 'slack'
cask 'telegram'
cask 'tunnelblick'
cask 'docker'
cask 'macpass'
cask 'vagrant'
cask 'vlc'
cask 'transmission'
cask 'resilio-sync'
