"-- Pathogen
execute pathogen#infect()
filetype plugin indent on

"-- General --
set number                     " Show line numbers
set ruler                      " Show row and column ruler information
set backspace=indent,eol,start " Fix backspace behavior

"-- Coloring --
syntax on                      " Enable syntax highlighting

"-- Syntax --
set modeline                   " Detect file types
set modelines=5                " Number of lines for filetype detection

"-- Programming --
set autoindent                 " Auto-indent new lines
set smartindent                " Enable smart-indent
set showmatch                  " Highlight matching brace

"-- Spaces/Tabs --
set expandtab                  " Expand tabulation
set shiftwidth=2               " Number of auto-indent spaces
set tabstop=2                  " Number of spaces for display tabs

"-- Searching --
set hlsearch                   " Highlight all search results
set ignorecase                 " Always case-insensetive
set smartcase                  " Enable smart-case search
